### ISSUE TITLE
Permission to update

### ISSUE THREAD

**Issue by Pepige0n** [marcoserenelli/SplashWater#1]
Helo I would like to update and add some features to this mod and hope that you will allow me to do thiss,
so i am asking for permission to use your code and improve it
hope you will answer soon
Pepige0n

**Comment by marcoserenelli** [comment]
Hi @Pepige0n,

Apologies for the delay in response. I've decided to update the mod to version 1.20 on my own.
However, going forward, you are welcome to use the code for the mod as you wish, provided that you cite it as the original mod.
Thank you!

marcoserenelli aka Mr_Awsaf
